Default: local
Disks:
  - DiskName: local
    LOCAL:
      Root: "./test"
  - DiskName: oss
    OSS:
      Bucket: "test"
      Endpoint: "oss-cn-hangzhou.aliyuncs.com"
      AccessKeyID: "AccessKeyID"
      AccessKeySecret: "AccessKeySecret"
  - DiskName: bos
    BOS:
      Ak: "Ak"
      Sk: "Sk"
      Endpoint: "https://bj.bcebos.com"
      Bucket: "test"
  - DiskName: cloudstorage
    CloudStorage:
      Bucket: "test"
      CredentialsFile: "credentials_file.json"
  - DiskName: cos
    COS:
      BucketURL: "https://bucket-id.cos.ap-beijing.myqcloud.com"
      SecretID: "SecretID"
      SecretKey: "SecretKey"
  - DiskName: kodo
    KODO:
      AccessKey: "AccessKey"
      SecretKey: "SecretKey"
      Bucket: "test"
